version: '3'
services:
    
    web-container:
        build: .
        ports:
            - "8080:80"
        volumes:
            - logvolume01:/var/log
        environment:
            - APP_NAME=web-app
            - APP_PORT=80
    
    redis-container:
        image: redis
volumes:
    logvolume01: {}